#!/usr/bin/env python

### Copyright (C) 2010 Peter Williams <peter_ono@users.sourceforge.net>
###
### This program is free software; you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation; version 2 of the License only.
###
### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.
###
### You should have received a copy of the GNU General Public License
### along with this program; if not, write to the Free Software
### Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

'''
Implimentation of quilt using the Python programming language
'''

import sys

from pyquilt_pkg import customization
from pyquilt_pkg import cmd_line

args = cmd_line.PARSER.parse_args()

customization.process_configuration_data(args.quiltrc)

sys.exit(args.run_cmd(args))
